#!/bin/bash
# =============================================================================
# Backlink Engine - Script d'installation automatique pour Hetzner VPS
# Ubuntu 24.04 | Docker + Nginx + PostgreSQL + Redis
# SSL géré par Cloudflare (proxy orange, mode "Full")
# =============================================================================
# Usage: scp deploy/setup-server.sh root@VOTRE_IP:/root/ && ssh root@VOTRE_IP "bash /root/setup-server.sh"
# =============================================================================

set -euo pipefail

DOMAIN="backlinks.life-expat.com"
APP_DIR="/opt/backlink-engine"
REPO="https://github.com/will383842/backlink-engine.git"

echo "============================================="
echo " Backlink Engine - Installation automatique"
echo "============================================="
echo ""

# ---------------------------------------------------------------------------
# 1. System update + essentials
# ---------------------------------------------------------------------------
echo "[1/6] Mise à jour du système..."
apt-get update -qq && apt-get upgrade -y -qq
apt-get install -y -qq curl git ufw fail2ban

# ---------------------------------------------------------------------------
# 2. Firewall
# ---------------------------------------------------------------------------
echo "[2/6] Configuration du firewall..."
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp
echo "y" | ufw enable

# ---------------------------------------------------------------------------
# 3. Install Docker
# ---------------------------------------------------------------------------
echo "[3/6] Installation de Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
fi
echo "Docker version: $(docker --version)"

# ---------------------------------------------------------------------------
# 4. Clone the repository
# ---------------------------------------------------------------------------
echo "[4/6] Clonage du dépôt..."
if [ -d "$APP_DIR" ]; then
    echo "Répertoire existe déjà, mise à jour..."
    cd "$APP_DIR" && git pull origin main
else
    git clone "$REPO" "$APP_DIR"
fi
cd "$APP_DIR"

# ---------------------------------------------------------------------------
# 5. Create .env file
# ---------------------------------------------------------------------------
echo "[5/6] Configuration de l'environnement..."
if [ ! -f .env ]; then
    # Generate secure passwords
    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
    JWT_SECRET=$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 64)
    WEBHOOK_SECRET=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
    INGEST_KEY=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)

    cat > .env << ENVEOF
# Auto-generated by setup-server.sh - $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Database
DATABASE_URL="postgresql://backlink:${POSTGRES_PASSWORD}@postgres:5432/backlink_engine?schema=public"
POSTGRES_USER=backlink
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=backlink_engine

# Redis
REDIS_URL="redis://redis:6379"

# JWT
JWT_SECRET="${JWT_SECRET}"

# MailWizz (à configurer plus tard)
MAILWIZZ_API_URL="https://mail.sos-expat.com/api"
MAILWIZZ_API_KEY="your-mailwizz-api-key"
MAILWIZZ_WEBHOOK_SECRET="${WEBHOOK_SECRET}"

# Claude AI (à configurer)
ANTHROPIC_API_KEY="sk-ant-..."

# Google Safe Browsing (optionnel)
GOOGLE_SAFE_BROWSING_API_KEY=""

# IMAP (à configurer plus tard)
IMAP_HOST="imap.example.com"
IMAP_PORT=993
IMAP_USER="replies@sos-expat.com"
IMAP_PASS=""

# Ingest API
INGEST_API_KEY="${INGEST_KEY}"

# Server
PORT=3000
NODE_ENV=production
LOG_LEVEL=info
CORS_ORIGIN="https://${DOMAIN}"
ENVEOF

    echo "  .env créé avec des mots de passe sécurisés."
    echo "  IMPORTANT: Éditez .env pour ajouter vos clés API (ANTHROPIC_API_KEY, etc.)"
else
    echo "  .env existe déjà, pas de modification."
fi

# ---------------------------------------------------------------------------
# 6. Start everything with Docker Compose
# ---------------------------------------------------------------------------
echo "[6/6] Lancement de l'application..."
cd "$APP_DIR"
docker compose up -d --build

# Wait for app to be healthy
echo "  Attente du démarrage..."
sleep 15

# Run Prisma migrations
echo "  Exécution des migrations Prisma..."
docker compose exec -T app npx prisma migrate deploy 2>/dev/null || \
    docker compose exec -T app npx prisma db push --accept-data-loss

echo ""
echo "============================================="
echo " Installation terminée !"
echo "============================================="
echo ""
echo " URL:        https://$DOMAIN"
echo " API:        https://$DOMAIN/api/health"
echo " Config:     $APP_DIR/.env"
echo ""
echo " IMPORTANT: Vérifiez que dans Cloudflare:"
echo "  - DNS: backlinks → $( curl -s ifconfig.me 2>/dev/null || echo 'VOTRE_IP' ) (proxy orange)"
echo "  - SSL/TLS → Full"
echo ""
echo " Prochaines étapes:"
echo "  1. Éditez .env pour ajouter vos clés API"
echo "     nano $APP_DIR/.env"
echo "  2. Relancez après modification:"
echo "     cd $APP_DIR && docker compose restart app"
echo "  3. Créez votre compte admin:"
echo "     curl -X POST https://$DOMAIN/api/auth/register \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"email\":\"votre@email.com\",\"password\":\"votre-mdp\",\"name\":\"Admin\"}'"
echo ""
echo " Commandes utiles:"
echo "  docker compose logs -f app    # Voir les logs"
echo "  docker compose restart        # Redémarrer tout"
echo "  docker compose down           # Arrêter tout"
echo "  cd $APP_DIR && git pull && docker compose up -d --build  # Mise à jour"
echo "============================================="
