#!/bin/bash
# =============================================================================
# Backlink Engine - Script d'installation automatique pour Hetzner VPS
# Ubuntu 24.04 | Docker + Nginx + SSL + PostgreSQL + Redis
# =============================================================================
# Usage: ssh root@VOTRE_IP "bash <(curl -s https://raw.githubusercontent.com/will383842/backlink-engine/main/deploy/setup-server.sh)"
# Ou: scp deploy/setup-server.sh root@VOTRE_IP:/root/ && ssh root@VOTRE_IP "bash /root/setup-server.sh"
# =============================================================================

set -euo pipefail

DOMAIN="backlinks.sos-expat.com"
EMAIL="williamsjullin@gmail.com"
APP_DIR="/opt/backlink-engine"
REPO="https://github.com/will383842/backlink-engine.git"

echo "============================================="
echo " Backlink Engine - Installation automatique"
echo "============================================="
echo ""

# ---------------------------------------------------------------------------
# 1. System update + essentials
# ---------------------------------------------------------------------------
echo "[1/8] Mise à jour du système..."
apt-get update -qq && apt-get upgrade -y -qq
apt-get install -y -qq curl git ufw fail2ban

# ---------------------------------------------------------------------------
# 2. Firewall
# ---------------------------------------------------------------------------
echo "[2/8] Configuration du firewall..."
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp
ufw allow 443/tcp
echo "y" | ufw enable

# ---------------------------------------------------------------------------
# 3. Install Docker
# ---------------------------------------------------------------------------
echo "[3/8] Installation de Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
fi
echo "Docker version: $(docker --version)"

# ---------------------------------------------------------------------------
# 4. Clone the repository
# ---------------------------------------------------------------------------
echo "[4/8] Clonage du dépôt..."
if [ -d "$APP_DIR" ]; then
    echo "Répertoire existe déjà, mise à jour..."
    cd "$APP_DIR" && git pull origin main
else
    git clone "$REPO" "$APP_DIR"
fi
cd "$APP_DIR"

# ---------------------------------------------------------------------------
# 5. Create .env file
# ---------------------------------------------------------------------------
echo "[5/8] Configuration de l'environnement..."
if [ ! -f .env ]; then
    # Generate secure passwords
    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
    JWT_SECRET=$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 64)
    WEBHOOK_SECRET=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
    INGEST_KEY=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)

    cat > .env << ENVEOF
# Auto-generated by setup-server.sh - $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Database
DATABASE_URL="postgresql://backlink:${POSTGRES_PASSWORD}@postgres:5432/backlink_engine?schema=public"
POSTGRES_USER=backlink
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=backlink_engine

# Redis
REDIS_URL="redis://redis:6379"

# JWT
JWT_SECRET="${JWT_SECRET}"

# MailWizz (à configurer plus tard)
MAILWIZZ_API_URL="https://mail.sos-expat.com/api"
MAILWIZZ_API_KEY="your-mailwizz-api-key"
MAILWIZZ_WEBHOOK_SECRET="${WEBHOOK_SECRET}"

# Claude AI (à configurer)
ANTHROPIC_API_KEY="sk-ant-..."

# Google Safe Browsing (optionnel)
GOOGLE_SAFE_BROWSING_API_KEY=""

# IMAP (à configurer plus tard)
IMAP_HOST="imap.example.com"
IMAP_PORT=993
IMAP_USER="replies@sos-expat.com"
IMAP_PASS=""

# Ingest API
INGEST_API_KEY="${INGEST_KEY}"

# Server
PORT=3000
NODE_ENV=production
LOG_LEVEL=info
CORS_ORIGIN="https://${DOMAIN}"
ENVEOF

    echo "  .env créé avec des mots de passe sécurisés."
    echo "  IMPORTANT: Éditez .env pour ajouter vos clés API (ANTHROPIC_API_KEY, etc.)"
else
    echo "  .env existe déjà, pas de modification."
fi

# ---------------------------------------------------------------------------
# 6. Build frontend locally (for Nginx to serve)
# ---------------------------------------------------------------------------
echo "[6/8] Build du frontend..."
docker run --rm -v "$APP_DIR/frontend:/app" -w /app node:20-alpine sh -c "npm ci && VITE_API_URL=https://${DOMAIN} npx vite build"

# ---------------------------------------------------------------------------
# 7. Get SSL certificate (initial - HTTP only)
# ---------------------------------------------------------------------------
echo "[7/8] Obtention du certificat SSL..."

# Start with HTTP-only nginx config first
cat > deploy/nginx-initial.conf << 'NGINXEOF'
server {
    listen 80;
    server_name backlinks.sos-expat.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'Backlink Engine - SSL setup in progress...';
        add_header Content-Type text/plain;
    }
}
NGINXEOF

# Start nginx temporarily for certbot challenge
docker run -d --name bl-nginx-temp \
    -p 80:80 \
    -v "$APP_DIR/deploy/nginx-initial.conf:/etc/nginx/conf.d/default.conf:ro" \
    -v bl_certbot_www:/var/www/certbot \
    nginx:alpine

# Get certificate
docker run --rm \
    -v bl_certbot_data:/etc/letsencrypt \
    -v bl_certbot_www:/var/www/certbot \
    certbot/certbot certonly \
    --webroot \
    --webroot-path=/var/www/certbot \
    --email "$EMAIL" \
    --agree-tos \
    --no-eff-email \
    -d "$DOMAIN"

# Stop temporary nginx
docker stop bl-nginx-temp && docker rm bl-nginx-temp

# Map certbot volumes to docker compose volume names
docker volume create --name backlink-engine_certbot_data 2>/dev/null || true
docker volume create --name backlink-engine_certbot_www 2>/dev/null || true

# Copy certbot data to compose volumes if needed
# (the compose file references these volumes)

echo "  Certificat SSL obtenu pour $DOMAIN"

# ---------------------------------------------------------------------------
# 8. Start everything with Docker Compose
# ---------------------------------------------------------------------------
echo "[8/8] Lancement de l'application..."
cd "$APP_DIR"
docker compose up -d --build

# Wait for app to be healthy
echo "  Attente du démarrage..."
sleep 15

# Run Prisma migrations
echo "  Exécution des migrations Prisma..."
docker compose exec -T app npx prisma migrate deploy 2>/dev/null || \
    docker compose exec -T app npx prisma db push --accept-data-loss

echo ""
echo "============================================="
echo " Installation terminée !"
echo "============================================="
echo ""
echo " URL:        https://$DOMAIN"
echo " API:        https://$DOMAIN/api/health"
echo " Config:     $APP_DIR/.env"
echo ""
echo " Prochaines étapes:"
echo "  1. Éditez .env pour ajouter vos clés API"
echo "     nano $APP_DIR/.env"
echo "  2. Relancez après modification:"
echo "     cd $APP_DIR && docker compose restart app"
echo "  3. Créez votre compte admin:"
echo "     curl -X POST https://$DOMAIN/api/auth/register \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"email\":\"votre@email.com\",\"password\":\"votre-mdp\",\"name\":\"Admin\"}'"
echo ""
echo " Commandes utiles:"
echo "  docker compose logs -f app    # Voir les logs"
echo "  docker compose restart        # Redémarrer tout"
echo "  docker compose down           # Arrêter tout"
echo "  cd $APP_DIR && git pull && docker compose up -d --build  # Mise à jour"
echo "============================================="
