#!/bin/bash
# =============================================================================
# SCRIPT : Créer les migrations Prisma initiales
# =============================================================================
# À exécuter sur le serveur APRÈS le premier déploiement
# Crée les migrations basées sur le schema.prisma actuel
# =============================================================================

set -euo pipefail

echo "============================================="
echo " CRÉATION DES MIGRATIONS PRISMA"
echo "============================================="
echo ""

cd /opt/backlink-engine

# ────────────────────────────────────────────────────────────
# 1. Vérifier que PostgreSQL est prêt
# ────────────────────────────────────────────────────────────

echo "[1/4] Vérification PostgreSQL..."

if docker exec bl-postgres pg_isready -U backlink -d backlink_engine > /dev/null 2>&1; then
    echo "  ✅ PostgreSQL prêt"
else
    echo "  ❌ PostgreSQL non accessible"
    exit 1
fi

# ────────────────────────────────────────────────────────────
# 2. Générer le client Prisma
# ────────────────────────────────────────────────────────────

echo ""
echo "[2/4] Génération du client Prisma..."

docker exec bl-app npx prisma generate

echo "  ✅ Client Prisma généré"

# ────────────────────────────────────────────────────────────
# 3. Appliquer le schema à la DB (db push)
# ────────────────────────────────────────────────────────────

echo ""
echo "[3/4] Application du schema à la DB..."

docker exec bl-app npx prisma db push --accept-data-loss

echo "  ✅ Schema appliqué à la DB"

# ────────────────────────────────────────────────────────────
# 4. Créer une migration baseline
# ────────────────────────────────────────────────────────────

echo ""
echo "[4/4] Création de la migration baseline..."

# Créer le dossier migrations
mkdir -p prisma/migrations/20260214_init

# Générer le SQL de migration depuis la DB actuelle
docker exec bl-app npx prisma migrate diff \
  --from-empty \
  --to-schema-datamodel prisma/schema.prisma \
  --script > prisma/migrations/20260214_init/migration.sql

# Créer le fichier migration_lock
cat > prisma/migrations/migration_lock.toml << 'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "postgresql"
EOF

echo "  ✅ Migration baseline créée"

# ────────────────────────────────────────────────────────────
# 5. Marquer la migration comme appliquée
# ────────────────────────────────────────────────────────────

echo ""
echo "Marquage de la migration comme appliquée..."

docker exec bl-app npx prisma migrate resolve --applied 20260214_init

echo "  ✅ Migration marquée comme appliquée"

# ────────────────────────────────────────────────────────────
# Résumé
# ────────────────────────────────────────────────────────────

echo ""
echo "============================================="
echo " MIGRATIONS CRÉÉES AVEC SUCCÈS"
echo "============================================="
echo ""
echo "Prochaines étapes :"
echo "  1. Commit les fichiers créés dans prisma/migrations/"
echo "     git add prisma/migrations/"
echo "     git commit -m 'feat: add initial database migrations'"
echo "     git push origin main"
echo ""
echo "  2. Sur les futurs déploiements, utiliser :"
echo "     npx prisma migrate deploy"
echo ""
echo "============================================="
